[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "hawnzug", email = "hawnzug@gmail.com"},
]
dependencies = [
    "epc>=0.0.5",
    "orjson>=3.8.6",
    "sexpdata==0.0.3",
    "six>=1.16.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}
